version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'typescript'
        versions: ['~5.3.3']
    open-pull-requests-limit: 10
