spring:
  docker:
    compose:
      enabled: true
      file: ./compose.yml
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/weather}
    username: ${SPRING_DATASOURCE_USERNAME:weather}
    password: ${SPRING_DATASOURCE_PASSWORD:weather}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none # Use 'update' for development
    show-sql: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        temp.use_jdbc_metadata_defaults: false
        id.new_generator_mappings: true
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        generate_statistics: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} %X{transactionId}- %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} %X{transactionId}- %msg%n'

server:
  port: ${SERVER_PORT:8082}

ilmateenistus:
  url: https://www.ilmateenistus.ee
