name: Build & Test

on:
  push:
  pull_request:

jobs:
  test:
    name: 🧪 Test with Gradle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [ 'unit', 'e2e' ]
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Start services with Docker Compose (for E2E tests)
        if: matrix.test-type == 'e2e'
        run: docker-compose -f docker-compose.yml -f docker-compose.e2e.yml up -d
      - name: Set CI environment variable
        run: echo "E2E=${{ matrix.test-type == 'e2e' }}" >> $GITHUB_ENV
      - name: Run Gradle test
        uses: eskatos/gradle-command-action@v3.4.2
        with:
          arguments: test --info -x bootJar -Dselenide.reportsFolder=build/reports/selenide ${{ matrix.test-type == 'e2e' && '-Pheadless=true' || '' }}
      - uses: actions/upload-artifact@v4.3.3
        if: always()
        with:
          name: ${{ format('Test reports and screenshots ({0})', matrix.test-type) }}
          path: |
            build/reports/tests
            build/reports/selenide

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    needs: [ test, build-docker ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
